<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Seeder para tabla Emisiones
         */

        $emisiones = [
            ['nombre' => 'Extracción de Carbón - Subterráneo', 'unidad_consumo' => 't', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '19.43', 'unidad_factor_emision_ch4' => 'kgCH4/t', 'incertidumbre_ch4_1' => '0.50000', 'incertidumbre_ch4_2' => '3.00000', 'fuente_bibliografica_ch4' => 'IPCC 2006. Corresponde a la sumatoria de las emisiones de minería y postextracción. Paginas 4.11 y 4.12; Se toma el valor mayor para ser conservador. ', 'tipo' => 'minería'],
            ['nombre' => 'Extracción de Carbón - Cielo Abierto', 'unidad_consumo' => 't', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '1.474', 'unidad_factor_emision_ch4' => 'kgCH4/t', 'incertidumbre_ch4_1' => '0.50000', 'incertidumbre_ch4_2' => '3.00000', 'fuente_bibliografica_ch4' => 'IPCC 2006. Corresponde a la sumatoria de las emisiones de minería y postextracción. Paginas 4.18 y 4.19; Se toma el valor mayor para ser conservador. ', 'tipo' => 'minería'],
            ['nombre' => 'CH4 en Cultivo de arroz', 'unidad_consumo' => 'Ha inund. x días', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '1.27', 'unidad_factor_emision_ch4' => 'kgCH4/Ha.inund.xdía', 'incertidumbre_ch4_1' => '0.40000', 'incertidumbre_ch4_2' => '0.70000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'embalse'],
            ['nombre' => 'Estanques o lagos de mas de 20 años', 'unidad_consumo' => 'Ha inundadas', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '141.1', 'unidad_factor_emision_ch4' => 'kgCH4/Ha', 'incertidumbre_ch4_1' => '0.90000', 'incertidumbre_ch4_2' => '1.06000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'embalse'],
            ['nombre' => 'Estanques o lagos salinos (menos de 20 años y salinidad de >18 ppt)', 'unidad_consumo' => 'Ha inundadas', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '30', 'unidad_factor_emision_ch4' => 'kgCH4/Ha', 'incertidumbre_ch4_1' => '0.90000', 'incertidumbre_ch4_2' => '1.06000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'embalse'],
            ['nombre' => 'Estanques o lagos agua dulce (menos de 20 años y salinidad de <18 ppt)', 'unidad_consumo' => 'Ha inundadas', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '183', 'unidad_factor_emision_ch4' => 'kgCH4/Ha', 'incertidumbre_ch4_1' => '0.90000', 'incertidumbre_ch4_2' => '1.06000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'embalse'],
            ['nombre' => 'Canales y zanjas inundadas', 'unidad_consumo' => 'Ha inundadas', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '416', 'unidad_factor_emision_ch4' => 'kgCH4/Ha', 'incertidumbre_ch4_1' => '0.90000', 'incertidumbre_ch4_2' => '1.06000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'embalse'],
            ['nombre' => 'Producción de coque', 'unidad_consumo' => 't', 'factor_emision_co2' => '0.089', 'unidad_factor_emision_co2' => 'kgCH4/t', 'incertidumbre_co2_1' => '4.00000', 'incertidumbre_co2_2' => '4.00000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de carbón vegetal', 'unidad_consumo' => 't', 'factor_emision_co2' => '40.3', 'unidad_factor_emision_co2' => 'kgCH4/t', 'incertidumbre_co2_1' => '0.68000', 'incertidumbre_co2_2' => '1.21000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Transporte de Gas Natural (Fugas CH4)', 'unidad_consumo' => 't', 'factor_emision_co2' => '1000', 'unidad_factor_emision_co2' => 'kgCH4/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.50000', 'fuente_bibliografica_co2' => 'Conversión', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de petróleo On-Shore (tecnologías de bajas emisiones)', 'unidad_consumo' => 'Barriles producidos', 'factor_emision_co2' => '0.46263911', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.30000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de petróleo On-Shore (tecnologías de altas emisiones)', 'unidad_consumo' => 'Barriles producidos', 'factor_emision_co2' => '0.545310016', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.30000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de petróleo Off-Shore ', 'unidad_consumo' => 'Barriles producidos', 'factor_emision_co2' => '0.391096979', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.30000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Transporte de petróleo en tuberías', 'unidad_consumo' => 'Barriles transport.', 'factor_emision_co2' => '0.000858506', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '1.00000', 'incertidumbre_co2_2' => '1.00000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Transporte de petróleo en camiones y trenes', 'unidad_consumo' => 'Barriles transport.', 'factor_emision_co2' => '0.003974563', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.50000', 'incertidumbre_co2_2' => '0.50000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Petróleo almacenado en tanques', 'unidad_consumo' => 'Barriles alimentados', 'factor_emision_co2' => '0.000317965', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.50000', 'incertidumbre_co2_2' => '0.50000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Refinación de petróleo', 'unidad_consumo' => 'Barriles refinados', 'factor_emision_co2' => '0.004769475', 'unidad_factor_emision_co2' => 'kgCH4/barril', 'incertidumbre_co2_1' => '0.50000', 'incertidumbre_co2_2' => '1.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de gas natural On-Shore (tecnologías de bajas emisiones)', 'unidad_consumo' => 'm3 producidos', 'factor_emision_co2' => '0.00254', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.20000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de gas natural On-Shore (tecnologías de altas emisiones)', 'unidad_consumo' => 'm3 producidos', 'factor_emision_co2' => '0.00409', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.20000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de gas natural Off-Shore ', 'unidad_consumo' => 'm3 producidos', 'factor_emision_co2' => '0.00294', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.20000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Tratamiento del gas natural (sin corrección de fugas en sistema)', 'unidad_consumo' => 'm3 tratados', 'factor_emision_co2' => '0.00183', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.10000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Tratamiento del gas natural (con corrección de fugas en sistema)', 'unidad_consumo' => 'm3 tratados', 'factor_emision_co2' => '0.00075', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.10000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Transporte del gas natural en tuberías (sin corrección de fugas en sistema)', 'unidad_consumo' => 'm3 transportados', 'factor_emision_co2' => '0.00336', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Transporte del gas natural en tuberías (con corrección de fugas en sistema)', 'unidad_consumo' => 'm3 transportados', 'factor_emision_co2' => '0.00129', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Almacenamiento del gas natural (sin corrección de fugas en sistema)', 'unidad_consumo' => 'm3 almacenados', 'factor_emision_co2' => '0.00067', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Almacenamiento del gas natural (con corrección de fugas en sistema)', 'unidad_consumo' => 'm3 almacenados', 'factor_emision_co2' => '0.00029', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '0.30000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Distribución y comercialización del gas natural (sin corrección de fugas en sistema)', 'unidad_consumo' => 'm3 comercializados', 'factor_emision_co2' => '0.00292', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '1.20000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Distribución y comercialización del gas natural (con corrección de fugas en sistema)', 'unidad_consumo' => 'm3 comercializados', 'factor_emision_co2' => '0.00062', 'unidad_factor_emision_co2' => 'kgCH4/m3', 'incertidumbre_co2_1' => '0.20000', 'incertidumbre_co2_2' => '1.20000', 'fuente_bibliografica_co2' => 'IPCC 2019 ', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de Cal Dolomítica', 'unidad_consumo' => 't', 'factor_emision_co2' => '860', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Calcita (CaCO3)', 'unidad_consumo' => 't', 'factor_emision_co2' => '439.71', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Magnesita (MgCO3)', 'unidad_consumo' => 't', 'factor_emision_co2' => '521.97', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Dolomita (CaMg(CO3)2)', 'unidad_consumo' => 't', 'factor_emision_co2' => '477.32', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Siderita (FeCO3)', 'unidad_consumo' => 't', 'factor_emision_co2' => '379.87', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Rhodochrosita (MnCO3)', 'unidad_consumo' => 't', 'factor_emision_co2' => '382.86', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Carbonato de sodio (Na2CO3)', 'unidad_consumo' => 't', 'factor_emision_co2' => '414.92', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Calcinación de Ankerita (Ca(Fe.Mg.Mn)(CO3)2)', 'unidad_consumo' => 't', 'factor_emision_co2' => '475.72', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.15000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de vidrio plano y recipientes', 'unidad_consumo' => 'kg', 'factor_emision_co2' => '0.21', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.60000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de fibra de vidrio', 'unidad_consumo' => 'kg', 'factor_emision_co2' => '0.25', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.60000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de vidrio especial (vajillas)', 'unidad_consumo' => 'kg', 'factor_emision_co2' => '0.1', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.60000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de vidrio especial (iluminación)', 'unidad_consumo' => 'kg', 'factor_emision_co2' => '0.2', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.60000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de vidrio especial (laboratorio y/o farmacia)', 'unidad_consumo' => 'kg', 'factor_emision_co2' => '0.03', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.60000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de Amoniaco', 'unidad_consumo' => 't NH3', 'factor_emision_co2' => '3273', 'unidad_factor_emision_co2' => 'kgCO2/ t NH3', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.05000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción Polipropileno (Gases quemados TEA)', 'unidad_consumo' => 't', 'factor_emision_co2' => '3137.578797', 'unidad_factor_emision_co2' => 'kgCO2/t', 'incertidumbre_co2_1' => '0.02000', 'incertidumbre_co2_2' => '0.50000', 'fuente_bibliografica_co2' => 'Cálculos realizados por Propilco', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Producción de Acido Nítrico', 'unidad_consumo' => 't', 'factor_emision_co2' => '9', 'unidad_factor_emision_co2' => 'kgN2O/t', 'incertidumbre_co2_1' => '0.10000', 'incertidumbre_co2_2' => '0.40000', 'fuente_bibliografica_co2' => 'IPCC 2006', 'factor_emision_ch4' => null, 'unidad_factor_emision_ch4' => null, 'incertidumbre_ch4_1' => null, 'incertidumbre_ch4_2' => null, 'fuente_bibliografica_ch4' => null, 'tipo' => 'industrial'],
            ['nombre' => 'Vertimientos industriales no tratados (solo para alcance 3)', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.025', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '1.04000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (PTAR aeróbica) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (PTAR aeróbica sobrecargada) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.075', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.66667', 'incertidumbre_ch4_2' => '1.33333', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Digestor anaeróbico) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.2', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '1.00000', 'incertidumbre_ch4_2' => '1.25000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Reactor anaeróbico) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.2', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '1.00000', 'incertidumbre_ch4_2' => '1.25000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Laguna anaeróbica < 2 mts) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.05', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.00000', 'incertidumbre_ch4_2' => '1.50000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Laguna anaeróbica > 2 mts) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.2', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '1.00000', 'incertidumbre_ch4_2' => '1.25000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos no tratados (solo para alcance 3)', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.06', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.58000', 'incertidumbre_ch4_2' => '1.04000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos a cloaca o alcantarilla estancada', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.3', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.58000', 'incertidumbre_ch4_2' => '1.33333', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos a cloaca o alcantarilla en movimiento (abierta o cerrada)', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '1.00000', 'incertidumbre_ch4_2' => '1.25000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (PTAR aeróbica) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Digestor anaeróbico) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Reactor anaeróbico) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.83066', 'incertidumbre_ch4_2' => '0.83066', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Laguna anaeróbica < 2 mts) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.024', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.83066', 'incertidumbre_ch4_2' => '0.83066', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos industriales tratados (Laguna anaeróbica > 2 mts) ', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '1.00000', 'incertidumbre_ch4_2' => '1.25000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (PTAR aeróbica) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00054', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (Digestor anaeróbico) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (Reactor anaeróbico) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (Laguna anaeróbica < 2 mts) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.024', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.83066', 'incertidumbre_ch4_2' => '0.83066', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (Laguna anaeróbica > 2 mts) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.384', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.83066', 'incertidumbre_ch4_2' => '0.83066', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Vertimientos domésticos tratados (Sistema séptico) ', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.15', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.78102', 'incertidumbre_ch4_2' => '0.78102', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Tratamiento de lodos orgánicos industriales', 'unidad_consumo' => 'kg DQO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.2', 'unidad_factor_emision_ch4' => 'kgCH4/kg DQO', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.39000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Tratamiento de lodos orgánicos domésticos', 'unidad_consumo' => 'kg DBO', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.48', 'unidad_factor_emision_ch4' => 'kgCH4/kg DBO', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.32000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos a relleno sanitario anaeróbico ', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.052590', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos a relleno sanitario semiaerobico ', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.026295', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos a vertedero >5mts profundidad', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.037865', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos a vertedero <5mts profundidad', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.018932', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos a disposición sin categorizar', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.028399', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Lodos aguas residuales a relleno sanitario anaeróbico ', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.016667', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos hospital a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.050000', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos alimentos a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.050000', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos textil a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.080000', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos madera a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.143333', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos pulpa y papel a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.040000', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2019', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos caucho a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.130000', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos construcción a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.013333', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Residuo solidos otras industrias a relleno sanitario anaeróbico', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.003333', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.05000', 'incertidumbre_ch4_2' => '0.30000', 'fuente_bibliografica_ch4' => 'IPCC 2006', 'tipo' => 'residuo'],
            ['nombre' => 'Quema a cielo abierto residuo solidos domiciliarios', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0065', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos domiciliarios (continua-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0000002', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos domiciliarios (continua-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos domiciliarios (por lotes-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00006', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos domiciliarios (por lotes-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.000237', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos industriales (continua-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0000002', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos industriales (continua-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos industriales (por lotes-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00006', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos industriales (por lotes-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.000237', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos hospitalarios (continua-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0000002', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos hospitalarios (continua-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos hospitalarios (por lotes-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00006', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos hospitalarios (por lotes-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.000237', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos lodos aguas residuales (continua-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0000002', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos lodos aguas residuales (continua-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos lodos aguas residuales (por lotes-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00006', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos lodos aguas residuales (por lotes-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.000237', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos residuo líquidos fósiles (continua-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.0000002', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos residuo líquidos fósiles (continua-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos residuo líquidos fósiles (por lotes-cargador mecánico)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.00006', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
            ['nombre' => 'Incineración controlada residuo solidos residuo líquidos fósiles (por lotes-lecho fluidizado)', 'unidad_consumo' => 'kg húmedo', 'factor_emision_co2' => null, 'unidad_factor_emision_co2' => null, 'incertidumbre_co2_1' => null, 'incertidumbre_co2_2' => null, 'fuente_bibliografica_co2' => null, 'factor_emision_ch4' => '0.000237', 'unidad_factor_emision_ch4' => 'kgCH4/kg húmedo', 'incertidumbre_ch4_1' => '0.10000', 'incertidumbre_ch4_2' => '1.00000', 'fuente_bibliografica_ch4' => 'IPCC 2019 ', 'tipo' => 'residuo'],
        ];

        DB::table('emisiones')->insert($emisiones);
    }
}
