version: "3"

services:
    db:
        build: .docker/mariadb
        container_name: db
        environment:
            MARIADB_USER: root
            MARIADB_ROOT_PASSWORD: 123
        volumes:
            - .docker/mariadb/mariadbdata:/var/lib/mysql
        ports:
            - "3307:3306"

    web:
        container_name: web
        build: .docker/php
        ports:
            - "4000:8000"
        volumes:
            - .:/app
        depends_on:
            - db
